edr_appli_client:
    prefix:   /appli
    resource: "@EDRAppliBundle/Resources/config/routing/client.yml"

edr_appli_etablissement:
    prefix:   /admin/etablissement
    resource: "@EDRAppliBundle/Resources/config/routing/etablissement.yml"

edr_appli_tag:
    prefix:   /admin/tag
    resource: "@EDRAppliBundle/Resources/config/routing/tag.yml"

edr_appli_avis:
    resource: "@EDRAppliBundle/Resources/config/routing/avis.yml"
    prefix:   /admin/avis

edr_appli_categorie:
    resource: "@EDRAppliBundle/Resources/config/routing/categorie.yml"
    prefix:   /admin/categorie

map:
    path: /api/map
    defaults: { _controller: EDRAppliBundle:Recherche:index }

accueil_admin:
    path: /admin/accueil
    defaults: { _controller: EDRAppliBundle:Appli:adminAccueil}