edr_appli_client:
    prefix:   /
    resource: "@EDRAppliBundle/Resources/config/routing/client.yml"

edr_appli_etablissement:
    prefix:   /appli/etablissement
    resource: "@EDRAppliBundle/Resources/config/routing/etablissement.yml"

edr_appli_tag:
    prefix:   /appli/tag
    resource: "@EDRAppliBundle/Resources/config/routing/tag.yml"

edr_appli_avis:
    resource: "@EDRAppliBundle/Resources/config/routing/avis.yml"
    prefix:   /appli/avis

edr_appli_categorie:
    resource: "@EDRAppliBundle/Resources/config/routing/categorie.yml"
    prefix:   /appli/categorie



map:
    path: /map
    defaults: { _controller: EDRAppliBundle:Recherche:index }
