edr_appli_etablissement:
    resource: "@EDRAppliBundle/Resources/config/routing/etablissement.yml"
    prefix:   /etablissement

edr_appli_home:
    path:     /
    defaults: { _controller: EDRAppliBundle:Appli:index }

edr_appli_etablissement:
    path:     /etablissements/{id}
    defaults:
        _controller: EDRAppliBundle:Appli:view
    requirements:
        id: \d+

