edr_appli:
    resource: "@EDRAppliBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /user

recherche:
    resource: "@EDRAppliBundle/Resources/config/routing.yml"
    prefix:  /appli/recherche
