edr_user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

edr_appli:
    resource: "@EDRAppliBundle/Resources/config/routing.yml"
    prefix:   /appli

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"




