<?php
namespace EDR\AppliBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends EntityRepository
{
    public function getAvis_etablissement($id_etab){

        return $this->getEntityManager()
            ->createQuery('SELECT a.commentaire, a.note 
                                FROM EDRAppliBundle:Avis a 
                                WHERE a.etablissement = :idEtab')
            ->setParameter('idEtab', $id_etab )
            ->getResult();
    }
}
