<?php

namespace EDR\AppliBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends EntityRepository
{
}
