<?php

namespace EDR\AppliBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    public function getAvis_etablissement($id_categorie){

        return $this->getEntityManager()
            ->createQuery('SELECT a.commentaire, a.note, a.favoris 
                                FROM EDRAppliBundle:Avis a 
                                WHERE a.categorie = :idcategorie')
            ->setParameter('idcategorie', $id_categorie )
            ->getResult();
    }

}
