<?php

namespace EDR\AppliBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends EntityRepository
{
    public function getEtabWithCategory($categoryName)
    {
        $qb = $this->createQueryBuilder('e');

        //jointure avec l'entité Categorie
        $qb
            ->innerJoin('e.categories', 'c', 'WITH', 'c.nom = :categoryName')
            ->setParameter('categoryName', $categoryName)
            ->addSelect('c')
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
