<?php

namespace EDR\AppliBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function getTag($id_tags){

        return $this->getEntityManager()
            ->createQuery('SELECT nom,
                                FROM EDRAppliBundle:Tag 
                                WHERE tag = :idEtab')
            ->setParameter('idtags', $id_tags )
            ->getResult();
    }
}
