edr_appli_home:
    path:     /accueil
    defaults: { _controller: EDRAppliBundle:Appli:accueil }

etab_category_show:
    path:     /{category}/{page}
    defaults:
        _controller: EDRAppliBundle:Etablissement:showByCategory
        page: 1
    requirements:
        page: '\d*'
    methods:  [GET, POST]